from jsonschema import ValidationError, validate


def aweme_validate(json_data: dict):
    SCHEMA = {
        "type": "object",
        "properties": {
            "id": {"type": "string"},
            "play_urls": {"type": "array"},
            "ext": {"type": "string"},
            "width": {"type": "number"},
            "height": {"type": "number"},
            "duration": {"type": "number"},
            "thumbnails": {"type": "array"},
            "comment_count": {"type": "number"},
            "digg_count": {"type": "number"},
            "share_count": {"type": "number"},
            "play_count": {"type": "number"},
            "create_time": {"type": "number"},
            "upload_date": {"type": "string"},
            "title": {"type": "string"},
            "description": {"type": "string"},
            "nick_name": {"type": "string"},
            "unique_id": {"type": "string"},
            "sec_uid": {"type": "string"},
            "user_id": {"type": "string"},
            "user_url": {"type": "string"},
            "profile_pics": {"type": "array"},
            "webpage_url": {"type": "string"},
            "follower_count": {"type": "number"},
            "heart_total": {"type": "string"},
            "challenge_list": {"type": "array"},
            "duet_info": {"type": "string"},
            "text_extra": {"type": "array"},
            "music_id": {"type": "string"},
            "music_title": {"type": "string"},
            "music_artist": {"type": "string"},
            "music_covers": {"type": "array"},
        },
        "required": [
            "challenge_list",
            "comment_count",
            "create_time",
            "description",
            "digg_count",
            "duet_info",
            "duration",
            "ext",
            "follower_count",
            "heart_total",
            "height",
            "id",
            "music_artist",
            "music_covers",
            "music_id",
            "music_title",
            "nick_name",
            "play_count",
            "play_urls",
            "profile_pics",
            "sec_uid",
            "share_count",
            "text_extra",
            "thumbnails",
            "title",
            "unique_id",
            "upload_date",
            "user_id",
            "user_url",
            "webpage_url",
            "width",
        ],
    }

    try:
        validate(instance=json_data, schema=SCHEMA)
    except ValidationError as e:
        print("Error validating json_data", e)
